---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.23
  amd64: ghcr.io/home-assistant/amd64-base:3.23
  armhf: ghcr.io/home-assistant/armhf-base:3.23
  armv7: ghcr.io/home-assistant/armv7-base:3.23
  i386: ghcr.io/home-assistant/i386-base:3.23
args:
  GODNS_VERSION: 3.3.4